# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20170227_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='C:\\Users\\haris\\Desktop\\Sudheer_Task/images/'),
        ),
    ]
